--[[

|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

______  ___   _____ _____ _____     ___ _________  ________ _   _ 
| ___ \/ _ \ /  ___|_   _/  __ \   / _ \|  _  \  \/  |_   _| \ | |
| |_/ / /_\ \\ `--.  | | | /  \/  / /_\ \ | | | .  . | | | |  \| |
| ___ \  _  | `--. \ | | | |      |  _  | | | | |\/| | | | | . ` |
| |_/ / | | |/\__/ /_| |_| \__/\  | | | | |/ /| |  | |_| |_| |\  |
\____/\_| |_/\____/ \___/ \____/  \_| |_/___/ \_|  |_/\___/\_| \_/
                                                                 
                                                                 
Created By (Konto343) 
A easy to use and simple admin system for misc. purposes

== How to use:
1. Place in ServerScriptService.
2. That's it. Should work after that.
3. Be free to add on any custom code that you want or configure settings.

|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

UPDATES:
2.0.1 (10/21/2024) = Fixed alot of things + 2% more modular + better ui
2.1.1 (10/24/2024) = fixed some more things, added proper 'anti-exploits' and cleaned up stuff
2.2.0 (11/1/2024) = add ui button for mobile (cat funny) and type scripted a little
2.3.0 (1/1/2025) = _BA was added a 'global' to basic admin. Now can be accessed by the client and server 
2.4.0 (1/3/2025) = Did some clean up and more optimaztions
2.5.0 (1/5/2025) = More optimizing, better, ui update
2.6.0 (7/2/2025) = Minor touches, stripped all tweens in UI, made VERY SIMLPE
2.7.0 (7/19) = Made UI cleaner, add type previews for args, and color coded ui
2.8-2.9 (7/26-27/25) = Did some things, "small" (big) changes to codebase and ui
3.0.0 = (Refactor some code, added --!strict to all modules)
3.0.1 = UI redesign FINAL FOR REAL, less richtext :)
3.1.0 = Most likely the final update, otherwise just additions to commands.
3.3.1 = Added vanish, unvanish and Auto-Vanish for admins.
]]

return {
    _VERSION = '3.3.2'
}